language: ruby
rvm:
  - 2.4.1

before_script:
  - chmod +x ./script/cibuild.sh

script: ./script/cibuild.sh

# branch whitelist, only for Github pages
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
branches:
  only:
  - gh-pages # test gh-pages branch
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up html-proofer install

sudo: false # route build to the container-based infrastructure for faster build

cache: bundler # caching bundler gem packages will speed up build

